[workspace]
members = ["mex-*"]
default-members = ["mex-core"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.226", features = ["derive"] }
ratatui = "0.29.0"
serde_json = "1.0.145"
